# Dockerfile for a compiled application. This assumes pre-published binaries. 
FROM mcr.microsoft.com/dotnet/runtime:6.0

COPY bin/Release/net6.0/publish .

ENTRYPOINT ["dotnet", "DotNetConsoleApp.dll"]